version: '3.5'

services:
  postgres:
    image: postgres:12.2-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      POSTGRES_DB: ${POSTGRES_DB:-database_development}
      # PGDATA: /data/postgres
    # volumes:
    #    - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  
  pgadmin:
    image: dpage/pgadmin4:4.21
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org # ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: admin # ${PGADMIN_DEFAULT_PASSWORD:-admin}
    # volumes:
    #    - pgadmin:/root/.pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    depends_on: 
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin: